Feature/csv
php-etl/spreadsheet-flow pull request #7
Opened 2021-03-24 16:15 UTC by sebprt

2021-03-31 08:26 UTC, clemzarch approved these changes

2021-03-31 08:26 UTC, clemzarch commented on tests/functional/CSV/Safe/ExtractorTest.php
> +use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;
on dirait que ce Factory est pas utilisé

2021-03-31 08:47 UTC, sebprt commented on tests/functional/CSV/Safe/ExtractorTest.php
> +use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;
Effectivement. C'est supprimé.

2021-03-31 09:40 UTC, programgames approved these changes

2021-03-31 15:40 UTC, gplanchat requested changes

2021-03-31 15:40 UTC, gplanchat commented on src/CSV/FingersCrossed/Extractor.php
> +        $this->reader->setEncoding($this->encoding);
Ces lignes auraient plus leur place en dehors de la classe, les propriétés `delimiter`, `enclosure` et `encoding ` ne sont utilisées nulle part ailleurs que dans le constructeur.

D'autre part, on modifie l'état d'un objet `reader`, ce qui aura des conséquences très difficiles à anticiper.

2021-03-31 15:40 UTC, gplanchat commented on src/CSV/FingersCrossed/Loader.php
> +        $this->writer->setFieldEnclosure($this->enclosure);
Idem que sur l'extracteur. Ces lignes auraient plus leur place en dehors de la classe, les propriétés `delimiter`, `enclosure` et `encoding` ne sont utilisées nulle part ailleurs que dans le constructeur.

D'autre part, on modifie l'état d'un objet `writer`, ce qui aura des conséquences très difficiles à anticiper.

2021-03-31 15:40 UTC, gplanchat commented on src/CSV/Safe/Extractor.php
> +        $this->reader->setEncoding($this->encoding);
Ces lignes auraient plus leur place en dehors de la classe, les propriétés `delimiter`, `enclosure` et `encoding ` ne sont utilisées nulle part ailleurs que dans le constructeur.

D'autre part, on modifie l'état d'un objet `reader`, ce qui aura des conséquences très difficiles à anticiper.

2021-03-31 15:40 UTC, gplanchat commented on src/CSV/Safe/Loader.php
> +        $this->writer->setFieldEnclosure($this->enclosure);
Ces lignes auraient plus leur place en dehors de la classe, les propriétés `delimiter`, `enclosure` et `encoding ` ne sont utilisées nulle part ailleurs que dans le constructeur.

D'autre part, on modifie l'état d'un objet `writer`, ce qui aura des conséquences très difficiles à anticiper.

2021-04-01 07:55 UTC, sebprt commented on src/CSV/FingersCrossed/Extractor.php
> +        $this->reader->setEncoding($this->encoding);
Supprimé

2021-04-01 07:56 UTC, sebprt commented on src/CSV/FingersCrossed/Loader.php
> +        $this->writer->setFieldEnclosure($this->enclosure);
Supprimé

2021-04-01 07:56 UTC, sebprt commented on src/CSV/Safe/Loader.php
> +        $this->writer->setFieldEnclosure($this->enclosure);
Supprimé

2021-04-01 08:40 UTC, gplanchat approved these changes

2021-04-01 12:22 UTC, merged